spring.application.name=notification-service
server.port=8083
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationservicedb
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka broker (Docker)
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
#spring.kafka.consumer.group-id=notification-service-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.notificationservice.event

spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587

spring.mail.username=api
spring.mail.password=e9497834dace332cee4faed860341378
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
